name: Hello Workflow

on:
  schedule:
    - cron: '20 17 * * *'  # This cron expression triggers the workflow every minute

jobs:
  print_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "hello!"
