name: Update Google Sheet

on:
  schedule:
    - cron: '* * * * *'  # Run every day at midnight

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --quiet gspread pandas oauth2client

      - name: Update website from Google Sheet
        run: 
          echo "Running update_sheet.py..."
          python update_sheet.py
          echo "update_sheet.py completed."
        env:
          GOOGLE_SHEET_ID: 1WKRWIkQ5qqr5caCEl5yaeHHuzDv_yF0fGpQs9dvBTgk
          API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY }}

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add content/*.json
          git commit -m "Update Google Sheets data [skip ci]"
  
      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          branch: ${{ github.ref }}
